services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: family-planner-db-dev
    environment:
      POSTGRES_USER: familyplanner
      POSTGRES_PASSWORD: familyplanner123
      POSTGRES_DB: family_planner
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U familyplanner"]
      interval: 5s
      timeout: 5s
      retries: 5

  # Backend API (Development mode with hot reload)
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: family-planner-backend-dev
    environment:
      DATABASE_URL: postgresql://familyplanner:familyplanner123@postgres:5432/family_planner?schema=public
      JWT_SECRET: super-secret-jwt-key-for-development
      JWT_EXPIRES_IN: 7d
      PORT: 3001
      NODE_ENV: development
      CORS_ORIGIN: http://localhost:5173
    ports:
      - "3001:3001"
    volumes:
      - ./backend/src:/app/src
      - ./backend/prisma:/app/prisma
    depends_on:
      postgres:
        condition: service_healthy
    command: sh -c "npx prisma generate && npx prisma migrate deploy && npx prisma db seed || true && npm run dev"

  # Frontend (Development mode with hot reload)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: family-planner-frontend-dev
    environment:
      VITE_API_URL: http://localhost:3001/api
    ports:
      - "5173:5173"
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public
      - ./frontend/index.html:/app/index.html
    depends_on:
      - backend

volumes:
  postgres_data:
    driver: local
