name: Deploy to Production

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Deployment environment'
        required: true
        default: 'staging'
        type: choice
        options:
          - staging
          - production

jobs:
  deploy:
    name: Deploy to ${{ github.event.inputs.environment }}
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install backend dependencies
      working-directory: ./backend
      run: npm ci

    - name: Install frontend dependencies
      working-directory: ./frontend
      run: npm ci

    - name: Build backend
      working-directory: ./backend
      run: npm run build

    - name: Build frontend
      working-directory: ./frontend
      run: npm run build
      env:
        VITE_API_URL: ${{ secrets.VITE_API_URL }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ secrets.DOCKER_REGISTRY || 'ghcr.io' }}
        username: ${{ secrets.DOCKER_USERNAME || github.actor }}
        password: ${{ secrets.DOCKER_PASSWORD || secrets.GITHUB_TOKEN }}

    - name: Build and push backend image
      uses: docker/build-push-action@v5
      with:
        context: ./backend
        push: true
        tags: |
          ${{ secrets.DOCKER_REGISTRY || 'ghcr.io' }}/${{ github.repository }}/backend:${{ github.sha }}
          ${{ secrets.DOCKER_REGISTRY || 'ghcr.io' }}/${{ github.repository }}/backend:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Build and push frontend image
      uses: docker/build-push-action@v5
      with:
        context: ./frontend
        push: true
        tags: |
          ${{ secrets.DOCKER_REGISTRY || 'ghcr.io' }}/${{ github.repository }}/frontend:${{ github.sha }}
          ${{ secrets.DOCKER_REGISTRY || 'ghcr.io' }}/${{ github.repository }}/frontend:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Deploy notification
      run: |
        echo "✅ Deployment to ${{ github.event.inputs.environment }} completed!"
        echo "Backend image: ${{ secrets.DOCKER_REGISTRY || 'ghcr.io' }}/${{ github.repository }}/backend:${{ github.sha }}"
        echo "Frontend image: ${{ secrets.DOCKER_REGISTRY || 'ghcr.io' }}/${{ github.repository }}/frontend:${{ github.sha }}"

    # Add your actual deployment steps here (e.g., SSH to server, kubectl apply, etc.)
    # Example for SSH deployment:
    # - name: Deploy to server
    #   uses: appleboy/ssh-action@master
    #   with:
    #     host: ${{ secrets.DEPLOY_HOST }}
    #     username: ${{ secrets.DEPLOY_USER }}
    #     key: ${{ secrets.DEPLOY_SSH_KEY }}
    #     script: |
    #       cd /opt/family-planner
    #       docker-compose pull
    #       docker-compose up -d
